### PR TITLE
modularized code, added workflows for linting formatting and building

### PR DESCRIPTION
**Pull request by mAmineChniti**
### TL;DR

Restructured project, added GitHub Actions, and updated configuration files.

### What changed?

- Moved source code from `lib/lib.ts` to `src/index.ts` and `src/types.ts`
- Added GitHub Actions workflows for build and lint/format
- Updated `package.json` scripts and main/types paths
- Modified `tsconfig.json` to reflect new source directory
- Updated `biome.json` with ignore patterns
- Adjusted test files to import from new source location

### Why make this change?

This restructuring improves the project's organization, making it easier to maintain and contribute to. The addition of GitHub Actions enhances the development workflow by automating build and code quality checks. Updated configuration files ensure proper functionality with the new structure, while the separation of types into a dedicated file improves code readability and maintainability.

---

### CODE REVIEW

**Comment by mAmineChniti** [comment]
Hey @ThatGuyJamal can i get some feedback on this and wether its helpful or not to the project, thank you in advance

**Comment by ThatGuyJamal** [comment]
Thanks for making the  PR @mAmineChniti so sorry I'm just seeing this! It's been a wild two weeks.

**Comment by ThatGuyJamal** [comment]
I like the changes, thanks for helping out! Do you have twitter I would love to talk more.

**Comment by mAmineChniti** [comment]
> I like the changes, thanks for helping out! Do you have twitter I would love to talk more.

yeah its @dada_buddha_

**Pull request merged**
